name: HA-5-11-24

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - run: echo "Start Build Process"

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "22.x"

      - name: check code and install dependencies
        run: |
          ls 
          node -v
          npm ci

      - name: build
        run: |
          npm run build
          ls

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: dist-files
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: dist-files
          path: ./dist

      - run: ls

      # Install AWS CLI
      - name: install-aws-cli-action
        uses: unfor19/install-aws-cli-action@v1

      # Configure AWS credentials
      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials

      # Verify AWS configuration
      - run: aws configure list-profiles

      # List S3 buckets to verify access
      - run: aws s3 ls --region eu-central-1

      # Sync build files to S3 bucket
      - run: aws s3 sync --region eu-central-1 ./dist s3://ha-5-11-24/
